/*
 * wubu_report.c — the HIVE-WALK REPORT GENERATOR (post-AN54 A2).
 * One command: lineage top-K, extinction events, policy changes,
 * graveyard reasons -> a markdown summary for humans.
 *
 * Reads the run's three artifacts:
 *   <base>.hive           (the fitness archive)
 *   <base>.prio           (the priority evidence)
 *   <base>.events.jsonl   (the run recorder's event stream)
 *
 * Usage: wubu_report <base> [--top K] [--out report.md]
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "wubu_diagnosis.h"
#include "wubu_priority_store.h"
#include "wubu_events.h"

int main(int argc, char **argv)
{
    if (argc < 2) {
        printf("usage: wubu_report <base> [--top K] [--out report.md]\n");
        return 1;
    }
    const char *base = argv[1];
    int top_k = 10;
    const char *out_path = NULL;
    for (int i = 2; i < argc; i++) {
        if (!strcmp(argv[i], "--top") && i + 1 < argc) top_k = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--out") && i + 1 < argc) out_path = argv[++i];
    }

    char hpath[640], ppath[640], epath[640];
    snprintf(hpath, sizeof(hpath), "%s.hive", base);
    snprintf(ppath, sizeof(ppath), "%s.prio", base);
    snprintf(epath, sizeof(epath), "%s.events.jsonl", base);

    /* the hive archive (the fitness history) */
    wubu_diag_loop_t loop;
    memset(&loop, 0, sizeof(loop));
    loop.ledger_cap = 4096; loop.grave_cap = 2048;
    loop.ledger = (wubu_fitness_cell_t *)calloc(loop.ledger_cap, sizeof(wubu_fitness_cell_t));
    loop.graveyard = (wubu_fitness_cell_t *)calloc(loop.grave_cap, sizeof(wubu_fitness_cell_t));
    int hn = wubu_diag_load(&loop, hpath);

    /* the priority evidence */
    wubu_priority_store_t prio;
    wubu_prio_init(&prio, 0.5f, 0.3f);
    FILE *pf = fopen(ppath, "rb");
    if (pf) {
        static char pbuf[8192];
        long pn = (long)fread(pbuf, 1, sizeof(pbuf), pf);
        fclose(pf);
        wubu_prio_load(&prio, pbuf, pn);
    }

    /* the event stream */
    wubu_event_t *events = (wubu_event_t *)calloc(4096, sizeof(wubu_event_t));
    int en = wubu_events_read(epath, events, 4096);

    /* the markdown output (to a file or stdout) */
    FILE *out = out_path ? fopen(out_path, "w") : stdout;
    if (!out) { printf("cannot open %s\n", out_path); return 1; }

    fprintf(out, "# Colony run report — %s\n\n", base);
    fprintf(out, "> generated by `wubu_report` (post-AN54 A2)\n\n");

    /* the headline numbers */
    fprintf(out, "## Headline\n\n");
    fprintf(out, "| metric | value |\n|---|---|\n");
    fprintf(out, "| fitness cells | %d |\n", hn > 0 ? hn : 0);
    fprintf(out, "| accepted | %d |\n", loop.n_accepted);
    fprintf(out, "| rejected (graveyard) | %d |\n", loop.grave_n);
    fprintf(out, "| events recorded | %d |\n", en);
    fprintf(out, "| priority cells | %d |\n", prio.n);
    int n_prot = 0;
    for (int i = 0; i < prio.n; i++) if (prio.cells[i].protected) n_prot++;
    fprintf(out, "| protected cells | %d |\n\n", n_prot);

    /* the lineage top-K by fitness (the survivors) */
    fprintf(out, "## Lineage top-%d (by fitness)\n\n", top_k);
    fprintf(out, "| rank | batch | cell | fitness | delta | verdict |\n|---|---|---|---|---|---|\n");
    /* simple top-K selection over the ledger */
    for (int k = 0; k < top_k && k < loop.ledger_n; k++) {
        int best = -1;
        float best_f = 1e9f;
        for (int i = 0; i < loop.ledger_n; i++) {
            int used = 0;
            for (int j = 0; j < k; j++) if (&loop.ledger[i] == &loop.ledger[j]) used = 1;
            if (!used && loop.ledger[i].fitness < best_f) { best_f = loop.ledger[i].fitness; best = i; }
        }
        if (best < 0) break;
        wubu_fitness_cell_t *c = &loop.ledger[best];
        fprintf(out, "| %d | %llu | %u | %.4f | %+.4f | %s |\n",
                k + 1, (unsigned long long)c->batch, c->cell_idx, c->fitness,
                c->delta, c->verdict == WUBU_DIAG_ACCEPT ? "accept" : "reject");
        /* the marker for the selection (swap into slot k) */
        wubu_fitness_cell_t tmp = loop.ledger[k];
        loop.ledger[k] = loop.ledger[best];
        loop.ledger[best] = tmp;
    }
    fprintf(out, "\n");

    /* the extinction events (from the lineage tracker's data — the
     * events carry the verdicts; rejected = graveyarded mutations) */
    fprintf(out, "## Graveyard (negative examples — %d)\n\n", loop.n_rejected);
    fprintf(out, "| batch | cell | fitness | delta |\n|---|---|---|---|\n");
    for (int i = 0; i < loop.grave_n && i < 20; i++) {
        wubu_fitness_cell_t *c = &loop.graveyard[i];
        fprintf(out, "| %llu | %u | %.4f | %+.4f |\n",
                (unsigned long long)c->batch, c->cell_idx, c->fitness, c->delta);
    }
    fprintf(out, "\n");

    /* the policy changes (the events carry the reason codes) */
    fprintf(out, "## Policy changes (the metadiag's reasons)\n\n");
    fprintf(out, "| round | reason | rate | floor |\n|---|---|---|---|\n");
    int shown = 0;
    int prev_reason = -1;
    for (int i = 0; i < en; i++) {
        if (events[i].policy_reason != prev_reason) {
            fprintf(out, "| %llu | %s | %.3f | %.3f |\n",
                    (unsigned long long)events[i].round,
                    events[i].policy_reason == 1 ? "loss rising" :
                    events[i].policy_reason == 2 ? "suite failing" :
                    events[i].policy_reason == 3 ? "relax" : "none",
                    events[i].mutation_rate, events[i].fitness_floor);
            prev_reason = events[i].policy_reason;
            shown++;
        }
    }
    if (shown == 0) fprintf(out, "| — | no policy changes | — | — |\n");
    fprintf(out, "\n");

    /* the attribution sample (A4: which cell + evidence justified) */
    fprintf(out, "## Mutation attribution (A4 — the evidence behind the accepts)\n\n");
    fprintf(out, "| round | cell | fisher | skill | traj | verdict |\n|---|---|---|---|---|---|\n");
    int att = 0;
    for (int i = 0; i < en && att < 15; i++) {
        if (events[i].verdict == 1) {
            fprintf(out, "| %llu | %u | %.3f | %u | %llu | accept |\n",
                    (unsigned long long)events[i].round, events[i].cell_idx,
                    events[i].prio_fisher, events[i].skill_version,
                    (unsigned long long)events[i].traj_id);
            att++;
        }
    }
    if (att == 0) fprintf(out, "| — | no accepted mutations | — | — | — | — |\n");
    fprintf(out, "\n");

    if (out_path) { fclose(out); printf("report -> %s\n", out_path); }
    free(loop.ledger);
    free(loop.graveyard);
    free(events);
    return 0;
}
